# Generated by Django 5.2.6 on 2025-10-05 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicgroup",
            name="number",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="Academic Group Number",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Department Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.academicgroup",
                verbose_name="Related group",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="User Settings"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="telegram_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Related user",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Subject Name"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(
                to="api.subject", verbose_name="Teacher To Subject"
            ),
        ),
    ]
