# Generated by Django 5.2.6 on 2025-10-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0002_alter_academicgroup_number_alter_department_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="subject",
            new_name="subjects",
        ),
    ]
